name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: sudo apt install -y tree python3
    - run: tree .
    - run: which gradle
    - run: gradle --version
    - run: gradle wrapper
    - run: bash ./gradlew build
    - run: which git
    - run: printenv
    - run: python3 renameartifact.py
    - run: printenv
    - run: tree .

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ADBCOPYPASTE_ARTIFACT_NAME }}
        path: ${{ env.ADBCOPYPASTE_ARTIFACT_FILENAME }}
