name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: sudo apt install -y tree python3
    - run: tree .
    - run: which gradle
    - run: gradle --version
    - run: gradle wrapper
    - run: bash ./gradlew build
    - run: python3 renameartifact.py
    - run: tree .
    - run: echo $GITHUB_ENV

    - uses: actions/upload-artifact@v2
      with:
        path: app/build/outputs/apk/debug/app-debug.apk
